2020-02-19 11:23:27,444 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-02-19 11:23:40,534 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:40,772 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:40,954 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:41,106 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:41,269 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:41,444 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:41,636 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:41,802 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:41,993 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:42,167 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:42,342 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:42,541 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:42,742 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:42,948 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:43,138 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:45,878 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:46,246 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:23:47,274 ERROR : Exception on /apropos [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 34, in apropos
    return render_template('apropos.html',title='yoyo')
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/apropos.html", line 1, in top-level template code
    {% extends "bae.html" %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bae.html
2020-02-19 11:28:19,516 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 10:28:17,820 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 10:28:43,658 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 10:32:00,262 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 10:51:43,135 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 10:55:36,561 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 10:55:56,418 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 10:56:05,893 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 11:06:59,588 INFO : DÃ©marrage de MonApplication [in /home/Etudiants/piat0005/s4/flask/app/__init__.py:44]
2020-03-04 11:07:41,239 ERROR : Exception on /user/yonathor [GET] [in /home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/Etudiants/piat0005/s4/flask/app/routes.py", line 95, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/Etudiants/piat0005/s4/flask/app/templates/user.html", line 34, in template
    {% elif not current_user.is_abonne(user) %}
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/Etudiants/piat0005/s4/flask/env_flask/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'elif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
